### ISSUE TITLE
关于 Task3 输入的疑问

### ISSUE THREAD

**Issue by uchenily** [arcsysu/SYsU-lang2#11]
作者你好,

我注意到任务3是完成从语法树到IR的翻译, 但 SYsU-lang2/task/3/README.md 中写到:

在禁用复活时, 使用 `任务 0 的标准答案输出，即 clang 预处理后的测例源代码文件` 作为输入, 这好像不对, 任务0的输出是 预处理后的源代码文件, 而不是 json 格式表示的语法树.

这似乎不是笔误, CMakeLists.txt 中也确实是这样做的:

SYsU-lang2/test/task3/CMakeLists.txt

```
# 为每个测例创建一个测试
if(TASK3_REVIVE)
  # 如果启用复活，则将前一个实验的标准答案作为输入
  // 这块儿没问题
  ...
  message(WARNING "在实验三复活：请在构建 task2-answer 后再使用 task3 的测试项目。")

else()
  # 否则以实验零的标准答案作为输入
  add_dependencies(task3-score task0-answer)

  foreach(_case ${_task3_cases})
    set(_output_dir ${CMAKE_CURRENT_BINARY_DIR}/${_case})
    file(MAKE_DIRECTORY ${_output_dir})
    // 这个地方我感觉输入是错误的
    add_test(NAME task3/${_case} COMMAND task3 ${_task0_out}/${_case}
                                         ${_output_dir}/output.ll)
    ...
  endforeach()

  message(WARNING "实验三复活已禁用，请在构建 task0-answer 后再使用 task3 的测试项目。")

endif()
```

我打印了其中一条命令是这样的: 

```bash
./build/task/3/task3 /path/to/SYsU-lang2/build/test/task0/functional-0/000_main.sysu.c /path/to/SYsU-lang2/build/test/task3/functional-0/000_main.sysu.c/output.ll
```

我理解在禁用复活的情况下实验三应该是使用实验二中我们自己的生成的json格式语法树作为答案(当然现有的转json的代码还不完整, 可能还需要补充一些额外的字段, 比如id)

希望帮忙解答一下, 谢谢!

**Comment by yhgu2000** [comment]
没有错误：禁用复活认为学生完成了从最开始到现在的所有工作，那么在每一个任务里，我们输入学生程序的都是预处理后的标准原始代码——同学们被期望自己完成前述所有实验的代码整合工作（这对于已经熟悉了自己写出代码的同学来说并不困难）

# 为什么框架不采用“调用同学们的task2结果然后输入给task3”的设计实现呢？

因为，对于一个实际的编译器来说，中间的语法树实际上只需是一个临时的内存形式，不需要非转换成JSON。如果我们定死了task3必须以JSON作为输入，那么同学们就必须写JSON反序列化的代码（做过的都知道，这是不必要又十分琐碎的工作，无聊又要花大量时间），因此我们task3仍然使用task0的原始输入，这样，已经完成前面实验的同学就不必再写反序列化JSON的代码了。

此外，在禁用复活时坚持使用原始输入还有其它好处：

- 学生可以对整体代码有更好的掌控，并且在实验全部完成后，他可以得到一份完整的（自己的）编译器代码，而不是被拆成几节的编译器
- 学生前一阶段的实现可能是有错误的，随着实验的深入，更多的测试用例可能会引入，他可能不得不在之后的阶段中弥补之前犯下的错误，如果我们框架强制给代码拆开，则会非常不方便学生去调试问题
- 运行可能有错误的学生代码对实验框架来说也是一项挑战，它可能导致框架无法正常工作，也很难给出精确有效的反馈信息——因为错误逃逸现象的存在，一个问题表现出来的地方可能与它的本质原因相距甚远，框架怎么知道是哪个实验环节出了错误？
