### ISSUE TITLE
Task2 Antlr 生成SYsULexer.tokens.hpp的依赖关系似乎不正确

### ISSUE THREAD

**Issue by unknown25001** [arcsysu/SYsU-lang2#6]
具体表现为：在SYsULexer.tokens加入新token后，SYsULexer.tokens.hpp并没有被重新build。

定位到问题位于task/2/antlr/CMakeLists.txt中的以下位置：
![image](https://github.com/arcsysu/SYsU-lang2/assets/43738187/1df4d7b0-8fbc-48cb-9b52-7c805bce6ce7)
此处SYsULexer.tokens.hpp的依赖错误设置为了.py文件，而非生成该文件所需的.tokens文件

**Comment by yhgu2000** [comment]
感谢反馈，已修复：https://github.com/arcsysu/SYsU-lang2/commit/f5b24b20311e5968d9232f70c5ac0a00966a2acd
